# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(80, 20))
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter_3 = QtWidgets.QSplitter(self.widget)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter = QtWidgets.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_initLF = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_initLF.setObjectName("lineEdit_initLF")
        self.chooseButton = QtWidgets.QPushButton(self.splitter)
        self.chooseButton.setObjectName("chooseButton")
        self.searchButton_actions_one_step = QtWidgets.QPushButton(self.splitter)
        self.searchButton_actions_one_step.setObjectName("searchButton_actions_one_step")
        self.searchButton_actions = QtWidgets.QPushButton(self.splitter)
        self.searchButton_actions.setObjectName("searchButton_actions")
        self.textEdit_display_actions = QtWidgets.QTextEdit(self.splitter_3)
        self.textEdit_display_actions.setObjectName("textEdit_display_actions")
        self.horizontalLayout_2.addWidget(self.splitter_3)
        self.tabWidget.addTab(self.widget, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.splitter_6 = QtWidgets.QSplitter(self.tab)
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName("splitter_6")
        self.splitter_5 = QtWidgets.QSplitter(self.splitter_6)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.label_2 = QtWidgets.QLabel(self.splitter_5)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_input_knowledge = QtWidgets.QLineEdit(self.splitter_5)
        self.lineEdit_input_knowledge.setObjectName("lineEdit_input_knowledge")
        self.searchButton_knowledge = QtWidgets.QPushButton(self.splitter_5)
        self.searchButton_knowledge.setObjectName("searchButton_knowledge")
        self.textEdit_display_knowledge = QtWidgets.QTextEdit(self.splitter_6)
        self.textEdit_display_knowledge.setObjectName("textEdit_display_knowledge")
        self.horizontalLayout_3.addWidget(self.splitter_6)
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.splitter_4 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.label_graph = QtWidgets.QLabel(self.splitter_4)
        self.label_graph.setText("")
        self.label_graph.setObjectName("label_graph")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_4)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.pushButton = QtWidgets.QPushButton(self.splitter_2)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.splitter_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.splitter_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.splitter_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.splitter_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.splitter_4)
        self.horizontalLayout.setStretch(0, 4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">潮流初始状态：</p></body></html>"))
        self.chooseButton.setText(_translate("MainWindow", "选择文件夹"))
        self.searchButton_actions_one_step.setText(_translate("MainWindow", "单步调整"))
        self.searchButton_actions.setText(_translate("MainWindow", "多步调整"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("MainWindow", "潮流收敛调整"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">输入知识：</p></body></html>"))
        self.searchButton_knowledge.setText(_translate("MainWindow", "查询"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "查询知识"))
        self.pushButton.setText(_translate("MainWindow", "随机负荷"))
        self.pushButton_2.setText(_translate("MainWindow", "潮流计算"))
        self.pushButton_3.setText(_translate("MainWindow", "搜索方案"))
        self.pushButton_4.setText(_translate("MainWindow", "帮助"))
        self.pushButton_5.setText(_translate("MainWindow", "退出"))

